//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MultiserviciosEntities : DbContext
    {
        public MultiserviciosEntities()
            : base("name=MultiserviciosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_GRAF_TABLA_HORAS2_Result> SP_GRAF_TABLA_HORAS2(Nullable<System.DateTime> fECHA_INICIO, Nullable<System.DateTime> fECHA_FIN)
        {
            var fECHA_INICIOParameter = fECHA_INICIO.HasValue ?
                new ObjectParameter("FECHA_INICIO", fECHA_INICIO) :
                new ObjectParameter("FECHA_INICIO", typeof(System.DateTime));
    
            var fECHA_FINParameter = fECHA_FIN.HasValue ?
                new ObjectParameter("FECHA_FIN", fECHA_FIN) :
                new ObjectParameter("FECHA_FIN", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GRAF_TABLA_HORAS2_Result>("SP_GRAF_TABLA_HORAS2", fECHA_INICIOParameter, fECHA_FINParameter);
        }
    
        public virtual ObjectResult<SP_GRAF_MEDIDA_DE_TIEMPO2_Result> SP_GRAF_MEDIDA_DE_TIEMPO2(Nullable<System.DateTime> fECHA_INICIO, Nullable<System.DateTime> fECHA_FIN)
        {
            var fECHA_INICIOParameter = fECHA_INICIO.HasValue ?
                new ObjectParameter("FECHA_INICIO", fECHA_INICIO) :
                new ObjectParameter("FECHA_INICIO", typeof(System.DateTime));
    
            var fECHA_FINParameter = fECHA_FIN.HasValue ?
                new ObjectParameter("FECHA_FIN", fECHA_FIN) :
                new ObjectParameter("FECHA_FIN", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GRAF_MEDIDA_DE_TIEMPO2_Result>("SP_GRAF_MEDIDA_DE_TIEMPO2", fECHA_INICIOParameter, fECHA_FINParameter);
        }
    
        public virtual ObjectResult<SP_GRAF_HORAS_TOTAL_Result> SP_GRAF_HORAS_TOTAL(Nullable<System.DateTime> fECHA_INICIO, Nullable<System.DateTime> fECHA_FIN)
        {
            var fECHA_INICIOParameter = fECHA_INICIO.HasValue ?
                new ObjectParameter("FECHA_INICIO", fECHA_INICIO) :
                new ObjectParameter("FECHA_INICIO", typeof(System.DateTime));
    
            var fECHA_FINParameter = fECHA_FIN.HasValue ?
                new ObjectParameter("FECHA_FIN", fECHA_FIN) :
                new ObjectParameter("FECHA_FIN", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GRAF_HORAS_TOTAL_Result>("SP_GRAF_HORAS_TOTAL", fECHA_INICIOParameter, fECHA_FINParameter);
        }
    
        public virtual ObjectResult<SP_TBL_DETALLE_GENERAL_TEC_Result> SP_TBL_DETALLE_GENERAL_TEC(Nullable<System.DateTime> fECHA_INICIO, Nullable<System.DateTime> fECHA_FIN)
        {
            var fECHA_INICIOParameter = fECHA_INICIO.HasValue ?
                new ObjectParameter("FECHA_INICIO", fECHA_INICIO) :
                new ObjectParameter("FECHA_INICIO", typeof(System.DateTime));
    
            var fECHA_FINParameter = fECHA_FIN.HasValue ?
                new ObjectParameter("FECHA_FIN", fECHA_FIN) :
                new ObjectParameter("FECHA_FIN", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TBL_DETALLE_GENERAL_TEC_Result>("SP_TBL_DETALLE_GENERAL_TEC", fECHA_INICIOParameter, fECHA_FINParameter);
        }
    
        public virtual ObjectResult<SP_TT_DISTR_DIAS_AUDITOR_POR_FASE_Result> SP_TT_DISTR_DIAS_AUDITOR_POR_FASE(Nullable<int> yEAR)
        {
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TT_DISTR_DIAS_AUDITOR_POR_FASE_Result>("SP_TT_DISTR_DIAS_AUDITOR_POR_FASE", yEARParameter);
        }
    
        public virtual ObjectResult<SP_TT_DISTR_DIAS_AUDITOR_POR_CONTROL_EQUIPO_Result> SP_TT_DISTR_DIAS_AUDITOR_POR_CONTROL_EQUIPO(Nullable<int> yEAR)
        {
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TT_DISTR_DIAS_AUDITOR_POR_CONTROL_EQUIPO_Result>("SP_TT_DISTR_DIAS_AUDITOR_POR_CONTROL_EQUIPO", yEARParameter);
        }
    
        public virtual ObjectResult<SP_TT_DETALLE_PROYECTO_ACTIVIDAD_Result> SP_TT_DETALLE_PROYECTO_ACTIVIDAD(Nullable<int> fECHA)
        {
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TT_DETALLE_PROYECTO_ACTIVIDAD_Result>("SP_TT_DETALLE_PROYECTO_ACTIVIDAD", fECHAParameter);
        }
    
        public virtual ObjectResult<SP_TT_DETALLE_ETAPAS_FASES_ACTIVIDADES_Result> SP_TT_DETALLE_ETAPAS_FASES_ACTIVIDADES(Nullable<int> fECHA)
        {
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TT_DETALLE_ETAPAS_FASES_ACTIVIDADES_Result>("SP_TT_DETALLE_ETAPAS_FASES_ACTIVIDADES", fECHAParameter);
        }
    
        public virtual ObjectResult<SP_TT_EQUIPO_ETAPAS_Result> SP_TT_EQUIPO_ETAPAS(Nullable<int> fECHA)
        {
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TT_EQUIPO_ETAPAS_Result>("SP_TT_EQUIPO_ETAPAS", fECHAParameter);
        }
    
        public virtual ObjectResult<SP_TT_DETALLE_FILTRAR_PROYECTO_Result> SP_TT_DETALLE_FILTRAR_PROYECTO(Nullable<int> yEAR)
        {
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TT_DETALLE_FILTRAR_PROYECTO_Result>("SP_TT_DETALLE_FILTRAR_PROYECTO", yEARParameter);
        }
    
        public virtual ObjectResult<SP_TT_DIAS_CONTROL_Result> SP_TT_DIAS_CONTROL(Nullable<int> yEAR)
        {
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TT_DIAS_CONTROL_Result>("SP_TT_DIAS_CONTROL", yEARParameter);
        }
    
        public virtual ObjectResult<SP_TT_ERROR_FASES_DISTRIBUCION_Result> SP_TT_ERROR_FASES_DISTRIBUCION(Nullable<System.DateTime> iNICIO, Nullable<System.DateTime> fIN)
        {
            var iNICIOParameter = iNICIO.HasValue ?
                new ObjectParameter("INICIO", iNICIO) :
                new ObjectParameter("INICIO", typeof(System.DateTime));
    
            var fINParameter = fIN.HasValue ?
                new ObjectParameter("FIN", fIN) :
                new ObjectParameter("FIN", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TT_ERROR_FASES_DISTRIBUCION_Result>("SP_TT_ERROR_FASES_DISTRIBUCION", iNICIOParameter, fINParameter);
        }
    }
}
