//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PROYECTOSIAV2Entities1 : DbContext
    {
        public PROYECTOSIAV2Entities1()
            : base("name=PROYECTOSIAV2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<ModuloRol> ModuloRol { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioModuloRol> UsuarioModuloRol { get; set; }
        public virtual DbSet<VIEW_ADMINISTRACION_USUARIOS> VIEW_ADMINISTRACION_USUARIOS { get; set; }
        public virtual DbSet<VIEW_USUARIOS_FORGOT_PASSWORD> VIEW_USUARIOS_FORGOT_PASSWORD { get; set; }
        public virtual DbSet<VIEW_USUARIOS_LOGIN> VIEW_USUARIOS_LOGIN { get; set; }
        public virtual DbSet<VIEW_WT_USUARIOS> VIEW_WT_USUARIOS { get; set; }
    
        public virtual ObjectResult<SP_MODULOS_USUARIOS_Result> SP_MODULOS_USUARIOS(Nullable<int> id_USUARIO)
        {
            var id_USUARIOParameter = id_USUARIO.HasValue ?
                new ObjectParameter("id_USUARIO", id_USUARIO) :
                new ObjectParameter("id_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MODULOS_USUARIOS_Result>("SP_MODULOS_USUARIOS", id_USUARIOParameter);
        }
    
        public virtual ObjectResult<SP_WT_ADMINISTRADOR_USUARIOS_Result> SP_WT_ADMINISTRADOR_USUARIOS(Nullable<int> iD_USUARIO)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_ADMINISTRADOR_USUARIOS_Result>("SP_WT_ADMINISTRADOR_USUARIOS", iD_USUARIOParameter);
        }
    
        public virtual ObjectResult<SP_WT_ROLES_MODULO_Result> SP_WT_ROLES_MODULO(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_ROLES_MODULO_Result>("SP_WT_ROLES_MODULO", iDParameter);
        }
    }
}
