//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_WT_ADMIN_MODULO_ROL
    {
        public string Modulos { get; set; }
        public int Administrador { get; set; }
        public int Gestor_de_Equipo { get; set; }
        public int Recurso { get; set; }
    }
}
